// Client Constants

export const CLIENT_LOGIN = 'CLIENT_LOGIN';
export const CLIENT_LOGIN_SUCCESS = 'CLIENT_LOGIN_SUCCESS';
export const CLIENT_LOGIN_FAILURE = 'CLIENT_LOGIN_FAILURE';

export const CLIENT_OTP_VERIFICATION = 'CLIENT_OTP_VERIFICATION';
export const CLIENT_OTP_VERIFICATION_SUCCESS = 'CLIENT_OTP_VERIFICATION_SUCCESS';
export const CLIENT_OTP_VERIFICATION_FAILURE = 'CLIENT_OTP_VERIFICATION_FAILURE';

export const CLIENT_GET_USER = 'CLIENT_GET_USER';
export const CLIENT_GET_USER_SUCCESS = 'CLIENT_GET_USER_SUCCESS';
export const CLIENT_GET_USER_FAILURE = 'CLIENT_GET_USER_FAILURE';

export const CLIENT_GET_DASHBOARD = 'CLIENT_GET_DASHBOARD';
export const CLIENT_GET_DASHBOARD_SUCCESS = 'CLIENT_GET_DASHBOARD_SUCCESS';
export const CLIENT_GET_DASHBOARD_FAILURE = 'CLIENT_GET_DASHBOARD_FAILURE';

export const UPDATE_PASSWORD = 'UPDATE_PASSWORD';
export const UPDATE_PASSWORD_SUCCESS = 'UPDATE_PASSWORD_SUCCESS';
export const UPDATE_PASSWORD_FAILURE = 'UPDATE_PASSWORD_FAILURE';

export const LOGOUT_CLIENT = 'LOGOUT_CLIENT';

export const CLIENT_FORGOT_PASSWORD = 'CLIENT_FORGOT_PASSWORD';
export const CLIENT_FORGOT_PASSWORD_SUCCESS = 'CLIENT_FORGOT_PASSWORD_SUCCESS';
export const CLIENT_FORGOT_PASSWORD_FAILURE = 'CLIENT_FORGOT_PASSWORD_FAILURE';

export const CLIENT_RESET_PASSWORD = 'CLIENT_RESET_PASSWORD';
export const CLIENT_RESET_PASSWORD_SUCCESS = 'CLIENT_RESET_PASSWORD_SUCCESS';
export const CLIENT_RESET_PASSWORD_FAILURE = 'CLIENT_RESET_PASSWORD_FAILURE';

export const CLIENT_EMPTY_FORGOT = 'CLIENT_EMPTY_FORGOT';


// Client Constants End


export const SIGNUP_LOCAL = "SIGNUP_LOCAL";
export const SIGNUP_LOCAL_SUCCESS = "SIGNUP_LOCAL_SUCCESS";
export const SIGNUP_LOCAL_FAILURE = "SIGNUP_LOCAL_FAILURE";

export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const OTP_VERIFICATION = 'OTP_VERIFICATION';
export const OTP_VERIFICATION_SUCCESS = 'OTP_VERIFICATION_SUCCESS';
export const OTP_VERIFICATION_FAILURE = 'OTP_VERIFICATION_FAILURE';

export const ADD_PROFILE = 'ADD_PROFILE';
export const ADD_PROFILE_SUCCESS = 'ADD_PROFILE_SUCCESS';
export const ADD_PROFILE_FAILURE = 'ADD_PROFILE_FAILURE';

export const GET_USER_DETAILS = 'GET_USER_DETAILS';
export const GET_USER_DETAILS_SUCCESS = 'GET_USER_DETAILS_SUCCESS';
export const GET_USER_DETAILS_FAILURE = 'GET_USER_DETAILS_FAILURE';

export const UPLOAD_FILE = 'UPLOAD_FILE';
export const UPLOAD_FILE_SUCCESS = 'UPLOAD_FILE_SUCCESS';
export const UPLOAD_FILE_FAILURE = 'UPLOAD_FILE_FAILURE';

export const EMPTY = 'EMPTY';

export const ADD_USER_DETAILS = 'ADD_USER_DETAILS';

export const LOGOUT = 'LOGOUT';



//  Categories apies
export const CATEGORIES_GET = 'CATEGORIES_GET';
export const CATEGORIES_GET_SUCCESS = 'CATEGORIES_GET_SUCCESS';
export const CATEGORIES_GET_FAILURE = 'CATEGORIES_GET_FAILURE';


export const GET_SEARCH = 'GET_SEARCH'
export const GET_SEARCH_SUCCESS = 'GET_SEARCH_SUCCESS'
export const GET_SEARCH_FAILURE = 'GET_SEARCH_FAILURE'

export const RESET_SEARCH = 'RESET_SEARCH'
export const SET_TABLE_DATA = 'SET_TABLE_DATA'

export const RESEND_OTP = 'RESEND_OTP'
export const RESEND_OTP_SUCCESS = 'RESEND_OTP_SUCCESS'
export const RESEND_OTP_FAILURE = 'RESEND_OTP_FAILURE'
export const RESEND_OTP_RESET = 'RESEND_OTP_RESET'

export const SET_STATUS_NULL = 'SET_STATUS_NULL'

export const ENRICH_DATA = 'ENRICH_DATA'
export const ENRICH_DATA_SUCCESS = 'ENRICH_DATA_SUCCESS'
export const ENRICH_DATA_FAILURE = 'ENRICH_DATA_FAILURE'

export const REQUESTS = 'REQUESTS'
export const REQUESTS_SUCCESS = 'REQUESTS_SUCCESS'
export const REQUESTS_FAILURE = 'REQUESTS_FAILURE'

export const ENRICH_DATA_DETAILS = 'ENRICH_DATA_DETAILS'
export const ENRICH_DATA_DETAILS_SUCCESS = 'ENRICH_DATA_DETAILS_SUCCESS'
export const ENRICH_DATA_DETAILS_FAILURE = 'ENRICH_DATA_DETAILS_FAILURE'

export const CREATE_PROJECT = 'CREATE_PROJECT'
export const CREATE_PROJECT_SUCCESS = 'CREATE_PROJECT_SUCCESS'
export const CREATE_PROJECT_FAILURE = 'CREATE_PROJECT_FAILURE'

export const GET_PROJECTS = 'GET_PROJECTS'
export const GET_PROJECTS_SUCCESS = 'GET_PROJECTS_SUCCESS'
export const GET_PROJECTS_FAILURE = 'GET_PROJECTS_FAILURE'


export const GET_PROJECT_VISITORS = 'GET_PROJECT_VISITORS'
export const GET_PROJECT_VISITORS_SUCCESS = 'GET_PROJECT_VISITORS_SUCCESS'
export const GET_PROJECT_VISITORS_FAILURE = 'GET_PROJECT_VISITORS_FAILURE'

export const LINKEDIN_ENRICH = 'LINKEDIN_ENRICH'
export const LINKEDIN_ENRICH_SUCCESS = 'LINKEDIN_ENRICH_SUCCESS'
export const LINKEDIN_ENRICH_FAILURE = 'LINKEDIN_ENRICH_FAILURE'

export const ADD_CREDITS = 'ADD_CREDITS'
export const ADD_CREDITS_SUCCESS = 'ADD_CREDITS_SUCCESS'
export const ADD_CREDITS_FAILURE = 'ADD_CREDITS_FAILURE'

export const GET_CREDITS = 'GET_CREDITS'
export const GET_CREDITS_SUCCESS = 'GET_CREDITS_SUCCESS'
export const GET_CREDITS_FAILURE = 'GET_CREDITS_FAILURE'

export const GET_API_KEYS = 'GET_API_KEYS'
export const GET_API_KEYS_SUCCESS = 'GET_API_KEYS_SUCCESS'
export const GET_API_KEYS_FAILURE = 'GET_API_KEYS_FAILURE'

export const GENERATE_API_KEY = 'GENERATE_API_KEY'
export const GENERATE_API_KEY_SUCCESS = 'GENERATE_API_KEY_SUCCESS'
export const GENERATE_API_KEY_FAILURE = 'GENERATE_API_KEY_FAILURE'

export const GET_SUB_USERS = 'GET_SUB_USERS'
export const GET_SUB_USERS_SUCCESS = 'GET_SUB_USERS_SUCCESS'
export const GET_SUB_USERS_FAILURE = 'GET_SUB_USERS_FAILURE'

export const ADD_SUB_USER = 'ADD_SUB_USER'
export const ADD_SUB_USER_SUCCESS = 'ADD_SUB_USER_SUCCESS'
export const ADD_SUB_USER_FAILURE = 'ADD_SUB_USER_FAILURE'

export const ADD_EMAIL = 'ADD_EMAIL'
export const ADD_EMAIL_SUCCESS = 'ADD_EMAIL_SUCCESS'
export const ADD_EMAIL_FAILURE = 'ADD_EMAIL_FAILURE'

export const GET_EMAILS = 'GET_EMAILS'
export const GET_EMAILS_SUCCESS = 'GET_EMAILS_SUCCESS'
export const GET_EMAILS_FAILURE = 'GET_EMAILS_FAILURE'

export const GET_TEMPLATES = 'GET_TEMPLATES'
export const GET_TEMPLATES_SUCCESS = 'GET_TEMPLATES_SUCCESS'
export const GET_TEMPLATES_FAILURE = 'GET_TEMPLATES_FAILURE'

export const SET_TEMPLATE = 'SET_TEMPLATE'
export const SET_TEMPLATE_SUCCESS = 'SET_TEMPLATE_SUCCESS'
export const SET_TEMPLATE_FAILURE = 'SET_TEMPLATE_FAILURE'

export const UPDATE_TEMPLATE = 'UPDATE_TEMPLATE'
export const UPDATE_TEMPLATE_SUCCESS = 'UPDATE_TEMPLATE_SUCCESS'
export const UPDATE_TEMPLATE_FAILURE = 'UPDATE_TEMPLATE_FAILURE'

export const DELETE_TEMPLATE = 'DELETE_TEMPLATE'
export const DELETE_TEMPLATE_SUCCESS = 'DELETE_TEMPLATE_SUCCESS'
export const DELETE_TEMPLATE_FAILURE = 'DELETE_TEMPLATE_FAILURE'

