export const SIGNUP_LOCAL="SIGNUP_LOCAL";
export const SIGNUP_LOCAL_SUCCESS="SIGNUP_LOCAL_SUCCESS";
export const SIGNUP_LOCAL_FAILURE="SIGNUP_LOCAL_FAILURE";

export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const OTP_VERIFICATION = 'OTP_VERIFICATION';
export const OTP_VERIFICATION_SUCCESS = 'OTP_VERIFICATION_SUCCESS';
export const OTP_VERIFICATION_FAILURE = 'OTP_VERIFICATION_FAILURE';

export const ADD_PROFILE = 'ADD_PROFILE';
export const ADD_PROFILE_SUCCESS = 'ADD_PROFILE_SUCCESS';
export const ADD_PROFILE_FAILURE = 'ADD_PROFILE_FAILURE';

export const GET_USER_DETAILS = 'GET_USER_DETAILS';
export const GET_USER_DETAILS_SUCCESS = 'GET_USER_DETAILS_SUCCESS';
export const GET_USER_DETAILS_FAILURE = 'GET_USER_DETAILS_FAILURE';

export const UPLOAD_FILE = 'UPLOAD_FILE';
export const UPLOAD_FILE_SUCCESS = 'UPLOAD_FILE_SUCCESS';
export const UPLOAD_FILE_FAILURE = 'UPLOAD_FILE_FAILURE';

export const EMPTY = 'EMPTY';

export const ADD_USER_DETAILS= 'ADD_USER_DETAILS';

export const LOGOUT = 'LOGOUT';



//  Categories apies
export const CATEGORIES_GET = 'CATEGORIES_GET';
export const CATEGORIES_GET_SUCCESS = 'CATEGORIES_GET_SUCCESS';
export const CATEGORIES_GET_FAILURE = 'CATEGORIES_GET_FAILURE';


export const GET_SEARCH='GET_SEARCH'
export const GET_SEARCH_SUCCESS='GET_SEARCH_SUCCESS'
export const GET_SEARCH_FAILURE='GET_SEARCH_FAILURE'

export const RESET_SEARCH='RESET_SEARCH'
export const SET_TABLE_DATA='SET_TABLE_DATA'

export const RESEND_OTP = 'RESEND_OTP'
export const RESEND_OTP_SUCCESS = 'RESEND_OTP_SUCCESS'
export const RESEND_OTP_FAILURE = 'RESEND_OTP_FAILURE'
export const RESEND_OTP_RESET = 'RESEND_OTP_RESET'

export const SET_STATUS_NULL = 'SET_STATUS_NULL'

export const ENRICH_DATA = 'ENRICH_DATA'
export const ENRICH_DATA_SUCCESS = 'ENRICH_DATA_SUCCESS'
export const ENRICH_DATA_FAILURE = 'ENRICH_DATA_FAILURE'

export const REQUESTS = 'REQUESTS'
export const REQUESTS_SUCCESS = 'REQUESTS_SUCCESS'
export const REQUESTS_FAILURE = 'REQUESTS_FAILURE'

export const ENRICH_DATA_DETAILS = 'ENRICH_DATA_DETAILS'
export const ENRICH_DATA_DETAILS_SUCCESS = 'ENRICH_DATA_DETAILS_SUCCESS'
export const ENRICH_DATA_DETAILS_FAILURE = 'ENRICH_DATA_DETAILS_FAILURE'

export const CREATE_PROJECT = 'CREATE_PROJECT'
export const CREATE_PROJECT_SUCCESS = 'CREATE_PROJECT_SUCCESS'
export const CREATE_PROJECT_FAILURE = 'CREATE_PROJECT_FAILURE'

export const GET_PROJECTS = 'GET_PROJECTS'
export const GET_PROJECTS_SUCCESS = 'GET_PROJECTS_SUCCESS'
export const GET_PROJECTS_FAILURE = 'GET_PROJECTS_FAILURE'


export const GET_PROJECT_VISITORS = 'GET_PROJECT_VISITORS'
export const GET_PROJECT_VISITORS_SUCCESS = 'GET_PROJECT_VISITORS_SUCCESS'
export const GET_PROJECT_VISITORS_FAILURE = 'GET_PROJECT_VISITORS_FAILURE'

export const LINKEDIN_ENRICH = 'LINKEDIN_ENRICH'
export const LINKEDIN_ENRICH_SUCCESS = 'LINKEDIN_ENRICH_SUCCESS'
export const LINKEDIN_ENRICH_FAILURE = 'LINKEDIN_ENRICH_FAILURE'

export const ADD_CREDITS = 'ADD_CREDITS'
export const ADD_CREDITS_SUCCESS = 'ADD_CREDITS_SUCCESS'
export const ADD_CREDITS_FAILURE = 'ADD_CREDITS_FAILURE'

export const GET_CREDITS = 'GET_CREDITS'
export const GET_CREDITS_SUCCESS = 'GET_CREDITS_SUCCESS'
export const GET_CREDITS_FAILURE = 'GET_CREDITS_FAILURE'

export const GET_API_KEYS = 'GET_API_KEYS'
export const GET_API_KEYS_SUCCESS = 'GET_API_KEYS_SUCCESS'
export const GET_API_KEYS_FAILURE = 'GET_API_KEYS_FAILURE'

export const GENERATE_API_KEY = 'GENERATE_API_KEY'
export const GENERATE_API_KEY_SUCCESS = 'GENERATE_API_KEY_SUCCESS'
export const GENERATE_API_KEY_FAILURE = 'GENERATE_API_KEY_FAILURE'

export const GET_SUB_USERS = 'GET_SUB_USERS'
export const GET_SUB_USERS_SUCCESS = 'GET_SUB_USERS_SUCCESS'
export const GET_SUB_USERS_FAILURE = 'GET_SUB_USERS_FAILURE'

export const ADD_SUB_USER = 'ADD_SUB_USER'
export const ADD_SUB_USER_SUCCESS = 'ADD_SUB_USER_SUCCESS'
export const ADD_SUB_USER_FAILURE = 'ADD_SUB_USER_FAILURE'
